# Generated by Django 4.2 on 2023-05-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0003_remove_user_apodo_user_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='Dueño',
            new_name='dueño',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='Monto',
            new_name='monto',
        ),
    ]
