# Generated by Django 4.2 on 2023-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_rename_dueño_transaccion_dueño_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='dueño',
            new_name='duenno',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_creación',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateField(default='2023-05-14'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categorias',
            field=models.CharField(max_length=200),
        ),
    ]
