# Generated by Django 4.2 on 2023-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0005_rename_dueño_transaccion_duenno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='categorias',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categoria',
            field=models.ManyToManyField(to='app_project.categoria'),
        ),
    ]
