# Generated by Django 4.2 on 2023-05-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0006_categoria_remove_transaccion_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.ManyToManyField(to='app_project.categoria'),
        ),
    ]
