# Generated by Django 4.2 on 2023-05-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0008_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_project.categoria'),
        ),
    ]
