# Generated by Django 4.2 on 2023-05-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0009_remove_transaccion_categoria_transaccion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateField(default='2023-05-30'),
        ),
    ]
